# ClusterIssuers for Let's Encrypt
# Copy this file to builder-space-argocd/environments/prod/infrastructure/cert-manager/

---
# Staging ClusterIssuer - Use for testing
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # Let's Encrypt staging server
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    
    # Email for urgent renewal and security notices
    # UPDATE: Replace with your email
    email: info@lightsphere.space
    
    # Secret to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging
    
    # HTTP-01 challenge solver
    solvers:
    - http01:
        ingress:
          class: nginx

---
# Production ClusterIssuer - Use after testing with staging
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    # Let's Encrypt production server
    server: https://acme-v02.api.letsencrypt.org/directory
    
    # Email for urgent renewal and security notices
    # UPDATE: Replace with your email
    email: info@lightsphere.space
    
    # Secret to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-production
    
    # HTTP-01 challenge solver
    solvers:
    - http01:
        ingress:
          class: nginx
